#!/bin/bash

mount -t tmpfs shmfs -o size=4g /dev/shm

cat /etc/security/limits.conf | grep -v oracle | tee /etc/security/limits.conf
chown -R oracle:oinstall /opt/oracle
chmod -R 777 /opt/oracle

date
echo "Installing database..."
su - oracle -c "cd /tmp/install/database/ && ./runInstaller -ignoreSysPrereqs -ignorePrereq -noconfig -silent -waitforcompletion -responseFile /tmp/install/db_install.rsp"
echo ""

date
echo "Finishing configuration..."
$ORACLE_HOME/root.sh
echo ""

date